;�X�L���̏��ݒ�
;Skin information
Name=RedzSoul-OpenTaiko-Skin
Version=0.1.1
Creator=RedzSoul (fork of Moshir's OpenTaiko Skin by Moshir)
Resolution=1920,1080
FontName=Fonts/Modified-DFPKanteiryu-XB.ttf
BoxFontName=Fonts/Modified-DFPKanteiryu-XB.ttf



; "#include �t�@�C����" ���߂��g�����Ƃ�
; �O���t�@�C����ǂݍ���Ŏg�p���邱�Ƃ��ł���悤�ɂȂ�܂�
#include OtherConfig.ini
#include TitleConfig.ini
#include ConfigConfig.ini
#include SongSelectConfig.ini
#include DaniSelectConfig.ini
#include SongLoadingConfig.ini
#include GameConfig.ini
#include Game4PConfig.ini
#include ResultConfig.ini
#include Result4PConfig.ini
#include AIResultConfig.ini
#include DanResultConfig.ini
#include TowerResultConfig.ini
#include HeyaConfig.ini
#include OnlineLoungeConfig.ini
#include TowerSelectConfig.ini
#include OpenEncyclopediaConfig.ini
#include NamePlateConfig.ini
#include ModalConfig.ini
#include Modal4PConfig.ini